TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += knr1050.db
DB += knr1050_errors.db
DATA += knr1050.proto

#=======================================
include $(TOP)/configure/RULES
